### ISSUE TITLE
Invalid address

### ISSUE THREAD

**Issue by ATolZi** [gertjaap/vertwallet-ios#33] opened 2017-12-18 15:32 UTC
Sending to my Electrum TOR wallet via scan returns this message:
![img_1680](https://user-images.githubusercontent.com/34648949/34113726-8b09633c-e408-11e7-978d-825c68f4d7f7.jpg)

**Comment by gertjaap** [comment] 2017-12-18 15:37
Duplicate of #10

**Closed as completed by gertjaap** 2017-12-18 15:37 UTC
Labels: duplicate
