### ISSUE TITLE
Importing Wallet Function - Wallet gets stuck with checking private key

### ISSUE THREAD

**Issue by gisad88** [gertjaap/vertwallet-ios#45] opened 2017-12-26 23:56 UTC
After scanning the code given, screen gets stuck with this screen
![img_8722](https://user-images.githubusercontent.com/33942532/34366745-563fe946-ea98-11e7-8f3d-37f7c024f564.PNG)

**Comment by gertjaap** [comment] 2017-12-27 06:21
Duplicate of #38

**Closed as completed by gertjaap** 2017-12-27 06:21 UTC
