### ISSUE TITLE
iPhone X Vertcoin Label

### ISSUE THREAD

**Issue by EricLegend** [gertjaap/vertwallet-ios#7] opened 2017-12-17 20:23 UTC
Home bar is coving the receiving UI label, see how discord did it might be something to consider https://imgur.com/gallery/LAsAX also the vertcoin logo with the test net uilabel at the top left is a bit high.

**Comment by gertjaap** [comment] 2017-12-18 14:23
Duplicate of #6

**Closed as completed by gertjaap** 2017-12-18 14:23 UTC
Labels: duplicate
