### ISSUE TITLE
Stuck at transaction details

### ISSUE THREAD

**Issue by sztlink** [gertjaap/vertwallet-ios#15] opened 2017-12-17 21:00 UTC
Just opened the wallet and clicked in the white rectangle with  the tiny blue arrow, got stuck in this screen:
https://i.imgur.com/JJmzpwT.png

iPhone 5s

**Comment by sztlink** [comment] 2017-12-17 21:23
It can be closed by swiping down

**Comment by sztlink** [comment] 2017-12-17 21:41
https://i.imgur.com/h3bR7Si.png

**Comment by gertjaap** [comment] 2017-12-18 14:44
Duplicate of #21 (same root cause - blank transaction details are unexpected, but caused by the Exchange rates not being fetched properly). Consolidating into single issue.

**Closed as completed by gertjaap** 2017-12-18 14:44 UTC
Labels: duplicate
